#lang: en
title: BlueBotPC LLC
email: matt@bluebotpc.com
description: Closed September 15th thru 18th
url: "https://www.bluebotpc.com"
permalink: pretty
favicon: /assets/img/favicon.ico
logo: /assets/img/logo_color.png

plugins:
  - jekyll-sitemap 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
