#lang: en
title: BlueBotPC LLC
tagline: Create Local Value
email: matt@bluebotpc.com
description: PC Repair & Managed WordPress
#baseurl: "https://bluebotpc.github.io/"
url: "https://www.bluebotpc.com"
permalink: pretty
favicon: /assets/img/favicon.ico
logo: /assets/img/logo_color.png

plugins:
  - jekyll-sitemap 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
